export const CQLType = {
  ascii: 'ascii',
  bigint: 'bigint',
  blob: 'blob',
  boolean: 'boolean',
  date: 'date',
  decimal: 'decimal',
  double: 'double',
  float: 'float',
  inet: 'inet',
  int: 'int',
  list: 'list',
  map: 'map',
  smallint: 'smallint',
  set: 'set',
  text: 'text',
  time: 'time',
  timestamp: 'timestamp',
  timeuuid: 'timeuuid',
  tinyint: 'tinyint',
  tuple: 'tuple',
  UDT: 'UDT',
  uuid: 'uuid',
  varchar: 'varchar',
  varint: 'varint',
}